// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYCd6V_jK7JZXr3rj7UlGTdisPloA-HDc',
    appId: '1:434112777646:web:52dec83c3e32c1a3910c3f',
    messagingSenderId: '434112777646',
    projectId: 'belleza2-d2ff1',
    authDomain: 'belleza2-d2ff1.firebaseapp.com',
    storageBucket: 'belleza2-d2ff1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyVHXg6OVOHWjJVWb7N1qlwmNy8Pxs9bA',
    appId: '1:434112777646:android:9f82b25d8d26a8b4910c3f',
    messagingSenderId: '434112777646',
    projectId: 'belleza2-d2ff1',
    storageBucket: 'belleza2-d2ff1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtve9nxPFHXK1-ZK_pdwr9fyvIha9RvCU',
    appId: '1:434112777646:ios:e9704bf7866fc9ec910c3f',
    messagingSenderId: '434112777646',
    projectId: 'belleza2-d2ff1',
    storageBucket: 'belleza2-d2ff1.firebasestorage.app',
    iosBundleId: 'com.example.paulette',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtve9nxPFHXK1-ZK_pdwr9fyvIha9RvCU',
    appId: '1:434112777646:ios:e9704bf7866fc9ec910c3f',
    messagingSenderId: '434112777646',
    projectId: 'belleza2-d2ff1',
    storageBucket: 'belleza2-d2ff1.firebasestorage.app',
    iosBundleId: 'com.example.paulette',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYCd6V_jK7JZXr3rj7UlGTdisPloA-HDc',
    appId: '1:434112777646:web:2a6fd8798ee1c1b4910c3f',
    messagingSenderId: '434112777646',
    projectId: 'belleza2-d2ff1',
    authDomain: 'belleza2-d2ff1.firebaseapp.com',
    storageBucket: 'belleza2-d2ff1.firebasestorage.app',
  );

}